AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Template for Deploying S3 Buckets, Transformation Lambda Function 
  and SQS Queue with Proper permissions

Resources:
  AWSWranglerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: aws-wrangler-layer
      Description: AWS Wrangler layer for AWS Wrangler Library
      ContentUri: aws_wrangler_layer/aws_wrangler_layer.zip
      CompatibleRuntimes:
        - python3.9

  BronzeTransformationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bronze_transformer/
      Handler: bronze_transformer.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Timeout: 900
      MemorySize: 1024
      LoggingConfig:
        LogFormat: JSON
      Environment:
        Variables:
          silver_bucket: !Ref SilverS3Bucket
          queue_name: !Ref RawBucketEventsQueue
      Layers:
        - !Ref AWSWranglerLayer
#         We can use the AWS Provided layer for AWS Wrangler but it cannot work with localstack
#         arn:aws:serverlessrepo:us-east-1:336392948345:applications/aws-data-wrangler-layer-py3-9
  BronzeS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: eon-bronze-bucket
      NotificationConfiguration:
          QueueConfigurations:
            - Event: s3:ObjectCreated:*
              Queue: !GetAtt RawBucketEventsQueue.Arn

  SilverS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: eon-silver-bucket

  RawBucketEventsQueue: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: EonMessageQueue

  SQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: SQS:SendMessage
            Resource: "*"
            Condition:
              ArnLike:
                aws:SourceArn: "arn:aws:s3:::!GetAtt BronzeS3Bucket.BucketName"
      Queues:
        - !Ref RawBucketEventsQueue

Outputs:
  BronzeTransformationFunction:
    Description: Bronze Function ARN
    Value: !GetAtt BronzeTransformationFunction.Arn
  BronzeTransformationFunctionIamRole:
    Description: Implicit IAM Role created for BronzeTransformationFunction function
    Value: !GetAtt BronzeTransformationFunction.Arn
