AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  test

  Sample SAM Template for test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
# Globals:
#   Function:
#     Timeout: 3
#     MemorySize: 128

#     # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
#     LoggingConfig:
#       LogFormat: JSON
Resources:
  AWSWranglerLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: aws-wrangler-layer
      Description: AWS Wrangler layer from GitHub
      ContentUri: awswrangler-layer-3.9.0-py3.11.zip
      CompatibleRuntimes:
        - python3.9

  BronzeTransformationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bronze_transformer/
      Handler: bronze_transformer.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Timeout: 900
      MemorySize: 1024
      Layers:
        - !Ref AWSWranglerLayer

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
      LoggingConfig:
        LogFormat: JSON

  BronzeS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: eon-bronze-bucket
      NotificationConfiguration:
          QueueConfigurations:
            - Event: s3:ObjectCreated:*
              Queue: !GetAtt RawBucketEventsQueue.Arn
    #close permissions to just upload a file

  SilverS3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: eon-silver-bucket
      #close permissions to read and write files to a lambda function

  RawBucketEventsQueue: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: EonMessageQueue

  SQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: SQS:SendMessage
            Resource: "*"
            Condition:
              ArnLike:
                aws:SourceArn: "arn:aws:s3:::!GetAtt BronzeS3Bucket.BucketName"
      Queues:
        - Ref: RawBucketEventsQueue

Outputs:
  HelloWorldFunction:
    Description: Bronze Function ARN
    Value: !GetAtt BronzeTransformationFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for BronzeTransformationFunction function
    Value: !GetAtt BronzeTransformationFunction.Arn
